Add options to support creating DATAGRAM2 and DATAGRAM3 sessions
The examples fail.

`datagram2` hangs indefnitely. `emissary` prints (removed times an extra messages):

INFO emissary::sam::pending::connection: create session session_id=SFssOJ3vctkcC1kR session_kind=Datagram2 destination=DestinationContext { .. }
INFO emissary::sam: start constructing new session session_id="SFssOJ3vctkcC1kR" destination_id=ihWW80NB version=V32
INFO emissary::tunnel: create tunnel pool config=TunnelPoolConfig { name: Allocated("SFssOJ3vctkcC1kR"), num_inbound: 2, num_inbound_hops: 3, num_outbound: 2, num_outbound_hops: 3 }
INFO emissary::tunnel::pool: outbound tunnel built name=SFssOJ3vctkcC1kR outbound_tunnel_id=2131378622
INFO emissary::tunnel::pool: inbound tunnel built name=SFssOJ3vctkcC1kR tunnel_id=1651634496
INFO emissary::sam::session: start active session session_id=SFssOJ3vctkcC1kR destination_id=ihWW80NB
INFO emissary::sam::pending::connection: create session session_id=SwmbHZ0nL0BLgM6Y session_kind=Datagram destination=DestinationContext { .. }
INFO emissary::sam: start constructing new session session_id="SwmbHZ0nL0BLgM6Y" destination_id=Wi-t5zVw version=V32
INFO emissary::tunnel: create tunnel pool config=TunnelPoolConfig { name: Allocated("SwmbHZ0nL0BLgM6Y"), num_inbound: 2, num_inbound_hops: 3, num_outbound: 2, num_outbound_hops: 3 }
INFO emissary::tunnel::pool: inbound tunnel built name=SwmbHZ0nL0BLgM6Y tunnel_id=3815947469
INFO emissary::tunnel::pool: inbound tunnel built name=SwmbHZ0nL0BLgM6Y tunnel_id=1534456951
INFO emissary::tunnel::pool: inbound tunnel built name=SFssOJ3vctkcC1kR tunnel_id=3232070012
WARN emissary::tunnel::pool: unhandled message name=SFssOJ3vctkcC1kR message_type=DeliveryStatus
INFO emissary::tunnel::pool: outbound tunnel built name=SwmbHZ0nL0BLgM6Y outbound_tunnel_id=3855482418
INFO emissary::sam::session: start active session session_id=SwmbHZ0nL0BLgM6Y destination_id=Wi-t5zVw
INFO emissary::sam::session: send datagram session_id=SwmbHZ0nL0BLgM6Y destination_id=ihWW80NB style=SamSessionKind::Datagram { .. }
WARN emissary::tunnel::pool: unhandled message name=SwmbHZ0nL0BLgM6Y message_type=DeliveryStatus
INFO emissary::tunnel::pool: outbound tunnel built name=SFssOJ3vctkcC1kR outbound_tunnel_id=3004486239
INFO emissary::sam::session: send datagram session_id=SFssOJ3vctkcC1kR destination_id=Wi-t5zVw style=SamSessionKind::Datagram { .. }

thread 'tokio-runtime-worker' (76549) panicked at emissary-core/src/sam/protocol/datagram/mod.rs:220:43:
slice index starts at 391 but ends at 14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

INFO emissary::tunnel::pool: tunnel pool shutting down name=SwmbHZ0nL0BLgM6Y
WARN emissary::tunnel::pool: failed to send shutdown confirmation to tunnel pool owner error=Closed
INFO emissary::tunnel::pool: tunnel pool shutting down name=SFssOJ3vctkcC1kR
WARN emissary::tunnel::pool: failed to send shutdown confirmation to tunnel pool owner error=Closed

`datagram3` is not supported by `emissary` yet, and so the example prints a
warning message about its protocol not being supported.